name: Update Flight Prices

on:
  schedule:
    - cron: '0 6 * * *'  # 每天 UTC 时间06:00运行一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run crawler script
      run: python crawler.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data/flights.json
        git commit -m "Update flight prices [skip ci]" || echo "No changes to commit"
        git push
      env:
        # 这里用默认GITHUB_TOKEN，无需自己配置
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
